### PR TITLE
Add December 2017 DAC codelist update to changelog

### PR DESCRIPTION
**Pull request by andylolz**
Refs IATI/IATI-Codelists-NonEmbedded#231.

### CODE REVIEW

**Comment by andylolz** [comment]
Any reason this was never merged? It doesn’t look like a changelog entry was ever added corresponding to these changes.

**Comment by andylolz** [comment]
I’ve fixed the merge conflict on this PR, just in case anyone fancies reviewing and/or merging it.

**Comment by samuele-mattiuzzo** [comment]
Hey @andylolz will ping the BAs to look at this, been quite the hectic period recently so might have slipped through the cracks!

@amy-silcock @PetyaKangalova @JoshStanleyDevInit can one of you take a quick look at this before it falls behind? ❤️

**Comment by andylolz** [comment]
> been quite the hectic period recently so might have slipped through the cracks!

Kk so, here’s the list of all open PRs to public IATI repos:
https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aiati

This is a really helpful view that github provides. It should make it easy to track PRs. I don’t mind about this one at all, but I wouldn’t want you to miss something important.

**Pull request merged**
