### PR TITLE
Update humanitarian.rst

### PR DESCRIPTION
**Pull request by amy-silcock**
First attempt to turn the new hum guidance into a RST file. Things to note:

- check how xml within a table presents on the website, we may need to rethink this and put the xml in the body of the text. Not in a table
- the two large tables were created with an online generator. To edit them, download the file and edit in a programme like atom. The width of the page on GH is too narrow hence the messy and hard to read layout when editing in GH. The GH 'preview' of these tables works well.

Please check that the content has been moved across as expected and that the links work. The google doc version is here: https://docs.google.com/document/d/1LeP0ncAF6_sBwRvCIk_5dPVSyMESSkiWkUyG10c-Je0/edit?usp=sharing

### CODE REVIEW

**Comment by akmiller01** [comment]
Here are all the warning messages I get when generating HTML from the RST @amy-silcock :
```
humanitarian.rst:78: WARNING: Inline target start-string without end-string.
humanitarian.rst:102: WARNING: Definition list ends without a blank line; unexpected unindent.
humanitarian.rst:106: WARNING: Definition list ends without a blank line; unexpected unindent.
humanitarian.rst:117: WARNING: Inline target start-string without end-string.
humanitarian.rst:154: WARNING: Inline target start-string without end-string.
humanitarian.rst:140: WARNING: Error parsing content block for the "list-table" directive: exactly one bullet list expected.

.. list-table::
  :widths: 28 28 44
:header-rows: 1

* - Name
- Type
- Example

* - Budget-not-provided (2.03+)
- Attribute
- <iati-activity humanitarian="1" budget-not-provided="3">
  
  This attribute can be used to explain why an activity does not contain any :doc:`activity budget </activity-budgets>` elements. It must only be used when no budget elements are reported.

Activities related to rapid onset emergencies often do not have an established budget. The budget-not-provided codelist provides three reasons why no budget is reported. In the case of humanitarian emergencies, _`Rapid Onset Emergency <https://iatistandard.org/en/iati-standard/codelists/budgetnotprovided>`__ (code 3), should be used.

Humanitarian activities, with expected transaction spend, which are not rapid onset emergencies should have a reported budget.
humanitarian.rst:173: WARNING: Bullet list ends without a blank line; unexpected unindent.
humanitarian.rst:161: WARNING: Error parsing content block for the "list-table" directive: two-level bullet list expected, but row 2 does not contain a second-level bullet list.

.. list-table::
  :widths: 28 28 44
:header-rows: 1

* - Name
- Type
- Example

* - Participating-org / type
- Attribute
- <participating-org ref="CC-CCC-123456789" role="4" type="24">
  <narrative>Organisation Name</narrative>
  </participating-org>
  humanitarian.rst:175: WARNING: Inline target start-string without end-string.
humanitarian.rst:227: WARNING: Inline target start-string without end-string.
humanitarian.rst:233: WARNING: Inline target start-string without end-string.
humanitarian.rst:214: WARNING: Error parsing content block for the "list-table" directive: exactly one bullet list expected.

.. list-table::
  :widths: 28 28 44
:header-rows: 1

* - Name
- Type
- Example

* - Sector
- Element
- <sector vocabulary="10" code="4" percentage="50" />
  <sector vocabulary="10" code="7" percentage="50" />
  
  The _`humanitarian response clusters <https://www.humanitarianresponse.info/en/about-clusters/what-is-the-cluster-approach>`__ are established by groups of humanitarian organisations to support coordination in a crisis response. Each cluster is formed of organisations (including both UN agencies and NGOs) tackling a main area of humanitarian action, e.g. water, health or logistics. The groups are designated by the Inter-Agency Standing Committee (IASC) and have clear responsibilities for coordination in emergencies.

Humanitarian Global Clusters can be specified in IATI data using the sector element. These can be provided alongside the OECD 5-digit DAC sector codes. The page :doc:`Activity Thematic Focus (Sectors) </activity-thematic-focus>` contains specific guidance on how to use sectors in IATI.

Multiple clusters can be added as long as a percentage split is included. The percentage split details the share of expected funding going to the particular cluster. All percentages from the same vocabulary must add up to 100%.

The Humanitarian Global Clusters can be provided using vocabulary 10 (according to the _`sector vocabulary codelist <https://iatistandard.org/en/iati-standard/codelists/sectorvocabulary>)`__. The codes can be downloaded by following the links on the vocabulary page. IATI does not maintain a separate list of the codes.
humanitarian.rst:267: WARNING: Inline target start-string without end-string.
humanitarian.rst:267: WARNING: Inline target start-string without end-string.
humanitarian.rst:295: WARNING: Inline target start-string without end-string.
humanitarian.rst:299: WARNING: Inline target start-string without end-string.
humanitarian.rst:299: WARNING: Inline target start-string without end-string.
humanitarian.rst:303: WARNING: Inline target start-string without end-string.
humanitarian.rst:328: WARNING: Inline target start-string without end-string.
humanitarian.rst:328: WARNING: Inline target start-string without end-string.
humanitarian.rst:331: WARNING: Inline target start-string without end-string.
humanitarian.rst:336: WARNING: Inline target start-string without end-string.
humanitarian.rst:339: WARNING: Inline target start-string without end-string.
humanitarian.rst:339: WARNING: Inline target start-string without end-string.
humanitarian.rst:342: WARNING: Inline target start-string without end-string.
humanitarian.rst:342: WARNING: Inline target start-string without end-string.
humanitarian.rst:352: WARNING: Inline target start-string without end-string.
humanitarian.rst:352: WARNING: Inline target start-string without end-string.
humanitarian.rst:364: WARNING: Inline target start-string without end-string.
humanitarian.rst:364: WARNING: Inline target start-string without end-string.
humanitarian.rst:381: WARNING: Inline target start-string without end-string.
humanitarian.rst:389: WARNING: Inline target start-string without end-string.
humanitarian.rst:389: WARNING: Inline target start-string without end-string.
humanitarian.rst:392: WARNING: Inline target start-string without end-string.
humanitarian.rst:392: WARNING: Inline target start-string without end-string.
humanitarian.rst:392: WARNING: Inline target start-string without end-string.
humanitarian.rst:395: WARNING: Inline target start-string without end-string.
humanitarian.rst:395: WARNING: Inline target start-string without end-string.
humanitarian.rst:413: WARNING: Inline target start-string without end-string.
```

**Comment by amy-silcock** [comment]
Thanks @akmiller01 please can you try running again?

**Comment by akmiller01** [comment]
> Thanks @akmiller01 please can you try running again?

Here's the output now:
```
humanitarian.rst:102: WARNING: Definition list ends without a blank line; unexpected unindent.
humanitarian.rst:106: WARNING: Definition list ends without a blank line; unexpected unindent.
humanitarian.rst:173: WARNING: Definition list ends without a blank line; unexpected unindent.
humanitarian.rst:: WARNING: Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.

```

**Comment by amy-silcock** [comment]
Thanks Alex, I've found an occasion with multiple spaces pre the <http. Might be that? No occurrence of no space though.

**Comment by akmiller01** [comment]
> Thanks Alex, I've found an occasion with multiple spaces pre the <http. Might be that? No occurrence of no space though.

Possibly! I can re-generate if you try pushing. And failing that I should be able to tinker a bit with it.

**Comment by akmiller01** [comment]
Still seeing the warning, as well as a Malformed table on line 418 (but it appears to render okay).

Also one thing to note (maybe this is what the warning is) iati-activity/@humanitarian is being interpreted as an email address:
image

**Comment by akmiller01** [comment]
@amy-silcock I think the link error is coming from line 261. Parenthesis embedded in the link syntax.
```
`sector vocabulary codelist <https://iatistandard.org/en/iati-standard/codelists/sectorvocabulary>)`__.
```

**Comment by akmiller01** [comment]
No more warnings @amy-silcock :1st_place_medal:

**Comment by amy-silcock** [comment]
@akmiller01 and @PetyaKangalova please can you approve so we can get this onto the website?

**Review by akmiller01 — APPROVED** [review]

**Review by PetyaKangalova — APPROVED** [review]
Checked content and looks good to me.

**Pull request merged**
